steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '--build-arg', 'APIKEY=$$_BLZ_APIKEY', '--build-arg', 'THREADS=2', '-t', 'gcr.io/$PROJECT_ID/simc:$SHORT_SHA', '.' ]
  secretEnv: ['_BLZ_APIKEY']
  timeout: 3600s

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/BlzApiKey/versions/1
    env: '_BLZ_APIKEY'

artifacts:
  objects:
    location: 'gs://us.artifacts.stately-rampart-199708.appspot.com/'
    paths: ['engine/simc']