steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/github.com/hot1989hot/simc:$SHORT_SHA', '--build-arg APIKEY=$_BLZ_APIKEY', '--build-arg THREADS=2', '.' ]


availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/BlzApiKey/versions/latest
    env: '_BLZ_APIKEY'

artifacts:
  objects:
    location: 'gs://us.artifacts.stately-rampart-199708.appspot.com/'
    paths: ['engine/simc']