steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ build gcr.io/$PROJECT_ID/simcbuilder .' ]

# - name: 'gcr.io/cloud-builders/docker'
#   entrypoint: 'bash'
#   args: [ '-c', 'docker build --build-arg APIKEY=$$BLZ_APIKEY --build-arg THREADS=2 -t gcr.io/$PROJECT_ID/simc:latest .' ]
#   secretEnv: ['BLZ_APIKEY']

- name: 'gcr.io/$PROJECT_ID/simcbuilder'
  entrypoint: '/bin/ash'
  args: ['-c', 'make -C ./engine optimized -j ${_THREADS} SC_DEFAULT_APIKEY=$$BLZ_APIKEY']
  secretEnv: ['BLZ_APIKEY']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/BlzApiKey/versions/1
    env: 'BLZ_APIKEY'

substitutions:
    _THREADS: '1'

artifacts:
  objects:
    location: 'gs://us.artifacts.stately-rampart-199708.appspot.com/binary/'
    paths: ['./engine/simc']

timeout: 3600s